[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "microsoft-kiota-authentication-azure"
authors = [{name = "Microsoft", email = "graphtooling+python@microsoft.com"}]
dependencies = [
    "aiohttp >=3.8.0",
    "azure-core >=1.21.1",
    "microsoft-kiota-abstractions >=1.0.0,<2.0.0",
    "opentelemetry-api >=1.20.0",
    "opentelemetry-sdk >=1.20.0",
]
license = {file = "LICENSE"}
readme = "README.md"
keywords = ["kiota", "openAPI", "Microsoft", "Graph"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: MIT License",
]
dynamic = ["version", "description"]

[project.urls]
homepage = "https://github.com/microsoft/kiota#readme"
repository = "https://github.com/microsoft/kiota-authentication-azure-python"
documentation = "https://microsoft.github.io/kiota/"

[tool.flit.module]
name = "kiota_authentication_azure"

[tool.mypy]
warn_unused_configs = true
files = "kiota_authentication_azure"
ignore_missing_imports = true

[tool.yapf]
based_on_style = "pep8"
dedent_closing_brackets = true
each_dict_entry_on_separate_line = true
column_limit = 100

[tool.isort]
profile = "hug"